"""add back the product table

Revision ID: 11eb9759f228
Revises: 88f23d563f71
Create Date: 2020-09-01 21:38:17.548272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11eb9759f228'
down_revision = '88f23d563f71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('productURL', sa.String(), nullable=False),
    sa.Column('currentPrice', sa.Integer(), nullable=True),
    sa.Column('userBudget', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
