"""drop product table for now to change primary key

Revision ID: 88f23d563f71
Revises: 0fb7c2967de7
Create Date: 2020-09-01 21:36:01.067681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88f23d563f71'
down_revision = '0fb7c2967de7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('userId', sa.INTEGER(), nullable=False),
    sa.Column('productURL', sa.VARCHAR(), nullable=False),
    sa.Column('currentPrice', sa.INTEGER(), nullable=True),
    sa.Column('userBudget', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('userId')
    )
    # ### end Alembic commands ###
